### ISSUE TITLE
Автоматизировать первичную настройку Gitea

### ISSUE THREAD

**Issue by LeKovr** [dopos/dcape#22]
После первого старта gitea требуется ручное выполнение действий
* подтверждение параметров инсталляции
* создание учетной записи администратора
* ~~создание организации, участники которой имеют доступ к приватным интерфейсам dcape~~
* ~~регистрация OAuth2  приложений (narra, drone) с последующим сохранением регистрационных данных в `.env`~~
* (опционально) создание токена для доступа к конфигурациям приложений из консоли

Все эти действия уже (или когда gitea это позволит) надо автоматизировать

**Comment by LeKovr** [comment]
Версия [2.0-rc3](../tree/v2.0-rc3) решила часть вопросов, формулировка задачи обновлена

**Comment by anp135** [comment]
Создание пользователя в gitea:
`gitea admin create-user --admin --username <> --password <> --email <>`
если это первый запуск, то вместо хотьбы по gitea /install можно сделать предварительно 
`gitea migration`
и потом создавать юзера

**Comment by LeKovr** [comment]
[any settings in app.ini can be set or overridden with an environment variable of the form: GITEA__SECTION_NAME__KEY_NAME](https://github.com/go-gitea/gitea/tree/main/contrib/environment-to-ini)

**Comment by LeKovr** [comment]
пытаюсь сконфить автоустановку на 1.19.1
`gitea migrate`
* `Unable to find configuration file: "/data/gitea/conf/app.ini"`
* `Database settings are missing from the configuration file: "/data/gitea/conf/app.ini".` (т.е. инфа из поста выше тут не работает)

Если создать app.ini как раньше и сделать  `gitea admin user create --admin `, после старта gitea все равно доступна только "Начальная конфигурация"

**Comment by LeKovr** [comment]
текущий статус по задаче
порядок установки
1. создать app.ini как раньше, но с добавлением `INSTALL_LOCK=true`
2. стартовать контейнер
3. создать админа `compose exec gitea su git -c 'gitea admin user create --admin...`
4. создать токен через API (в этот момент уже все работает)

**Comment by LeKovr** [comment]
Все задачи решены на ветке v3
