### ISSUE TITLE
Ошибка установки

### ISSUE THREAD

**Issue by ol2866** [dopos/dcape#32]
делаем по мануалу:
_git clone -b v2 --single-branch --depth 1 https://github.com/dopos/dcape.git
cd dcape
make init DCAPE_DOMAIN=ТЕСТ.ДОМЕН.РУ_
и получаем:
_docker build -t dcape-compose --build-arg DRONE_ROOT=/opt/dcape/apps/drone  ./apps/drone
unable to prepare context: path "./apps/drone" not found
make: *** [Makefile:152: compose] Error 1__

хотя, path  этот есть...что бы это значило?

**Comment by LeKovr** [comment]
Под Ubuntu не воспроизводится.
Какие версии linux и docker?

**Comment by ol2866** [comment]
на 2х серверах нормально поставил:
*  Ubuntu 22.04,  docker 20.10.17, build 100c701
*  Ubuntu 22.04,  docker 20.10.17, build 100c701
а на этом ошибка:
Ubuntu 22.04,  docker 20.10.24, build 297e128
  
>Пятница, 19 мая 2023, 10:59 +03:00 от Aleksei Kovrizhkin ***@***.***>:
> 
> 
>Под Ubuntu не воспроизводится.
>Какие версии linux и docker?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <dopos/dcape/issues/32/1554193094 @ github . com> 
 
 
С уважением,
Олег
***@***.***

**Comment by LeKovr** [comment]
Я тестирую на Docker Engine - Community
 Version:           23.0.6

Похоже, проблема не в версии docker. Еще варианты - права на /opt или настройки docker..
Без связи с dcape, для чего-то другого на этом хосте `docker build` отрабатывает?

**Comment by ol2866** [comment]
docker криво стоял, переставил - заработало...осталось понять как прописать DNS

**Comment by LeKovr** [comment]
> переставил - заработало...

отлично, закрываю

> осталось понять как прописать DNS

Я настроил [обсуждения](https://github.com/orgs/dopos/discussions), предлагаю там обсудить детали
